import { mkdir, readFile, writeFile } from "node:fs/promises";
import { basename, dirname, resolve } from "node:path";
import { inlineRelativeImports, stripCoreImports, stripTypeImports } from "./inline.js";
import { ENTRY_SOURCE, SHIM_SOURCE } from "./shim.js";

export interface ExportK6Options {
  /** Absolute or cwd-relative path to the `.journey.ts` file. */
  journeyFile: string;
  /** Output path for the emitted k6 script. Defaults to `<journey>.k6.js` next to the source. */
  outFile?: string;
}

export interface ExportK6Result {
  outFile: string;
  source: string;
}

const HEADER = `// AUTO-GENERATED BY @journey/k6-adapter — do not edit by hand.
// Usage: JOURNEY_BASE_URL=https://api.example.com k6 run <this-file>
`;

export async function exportToK6(opts: ExportK6Options): Promise<ExportK6Result> {
  const journeyPath = resolve(process.cwd(), opts.journeyFile);
  const rawSource = await readFile(journeyPath, "utf8");

  const withoutTypeImports = stripTypeImports(rawSource);
  const inlined = await inlineRelativeImports(withoutTypeImports, journeyPath);
  const withoutCore = stripCoreImports(inlined);

  const outFile = opts.outFile
    ? resolve(process.cwd(), opts.outFile)
    : resolve(dirname(journeyPath), `${basename(journeyPath).replace(/\.journey\.ts$/, "")}.k6.js`);

  const source = [
    HEADER,
    SHIM_SOURCE,
    "// ===== user journey =====",
    withoutCore.trimStart(),
    ENTRY_SOURCE,
  ].join("\n");

  await mkdir(dirname(outFile), { recursive: true });
  await writeFile(outFile, source, "utf8");
  return { outFile, source };
}
