import { mkdir, readFile, writeFile } from "node:fs/promises";
import { basename, dirname, resolve } from "node:path";
import { transform } from "esbuild";
import { inlineRelativeImports, stripCoreImports, stripTypeImports } from "./inline.js";
import { ENTRY_SOURCE, SHIM_SOURCE } from "./shim.js";

export interface ExportK6Options {
  /** Absolute or cwd-relative path to the `.journey.ts` file. */
  journeyFile: string;
  /** Output path for the emitted k6 script. Wins over `outDir` when both are set. */
  outFile?: string;
  /** Output directory; emitted file is `<outDir>/<basename>.k6.js`. Ignored when `outFile` is set. */
  outDir?: string;
  /**
   * k6 options block to bake into the emitted script as `export const options = {...}`.
   * Same shape as `JourneyOptions['k6']` from `@journey/core`; kept loose here so the
   * adapter does not pull a runtime dep on core. JSON-serialized verbatim.
   */
  k6Options?: Record<string, unknown>;
}

export interface ExportK6Result {
  outFile: string;
  source: string;
}

const HEADER = `// AUTO-GENERATED BY @journey/k6-adapter — do not edit by hand.
// Usage: JOURNEY_BASE_URL=https://api.example.com k6 run <this-file>
`;

export async function exportToK6(opts: ExportK6Options): Promise<ExportK6Result> {
  const journeyPath = resolve(process.cwd(), opts.journeyFile);
  const rawSource = await readFile(journeyPath, "utf8");

  const withoutTypeImports = stripTypeImports(rawSource);
  const inlined = await inlineRelativeImports(withoutTypeImports, journeyPath);
  const withoutCore = stripCoreImports(inlined);

  // The inlined user code is still TypeScript — generated `endpoints.ts` carries
  // `type` aliases, `as unknown as` casts, `as const`, etc. k6's JS engine (goja)
  // can't parse those, so strip all type syntax to plain JS. Import/export lines
  // are already gone (stripped above + rewritten by the inliner), so a bare
  // `transform` with the TS loader just erases types.
  const { code: userCode } = await transform(withoutCore, {
    loader: "ts",
    format: "esm",
  });

  const fileBase = basename(journeyPath).replace(/\.journey\.ts$/, "");
  const outFile = opts.outFile
    ? resolve(process.cwd(), opts.outFile)
    : opts.outDir
      ? resolve(process.cwd(), opts.outDir, `${fileBase}.k6.js`)
      : resolve(dirname(journeyPath), `${fileBase}.k6.js`);

  const optionsBlock = opts.k6Options
    ? `export const options = ${JSON.stringify(opts.k6Options, null, 2)};\n`
    : "";

  const source = [
    HEADER,
    SHIM_SOURCE,
    optionsBlock,
    "// ===== user journey =====",
    userCode.trimStart(),
    ENTRY_SOURCE,
  ].join("\n");

  await mkdir(dirname(outFile), { recursive: true });
  await writeFile(outFile, source, "utf8");
  return { outFile, source };
}
