// Sample data: Ledger payments API
const LEDGER_ENDPOINTS = [
  { method: 'POST',   path: '/v1/payments',                          tag: 'Payments',     summary: 'Create payment',          deprecated: false },
  { method: 'GET',    path: '/v1/payments',                          tag: 'Payments',     summary: 'List payments',           deprecated: false },
  { method: 'GET',    path: '/v1/payments/{id}',                     tag: 'Payments',     summary: 'Retrieve payment',        deprecated: false },
  { method: 'POST',   path: '/v1/payments/{id}/capture',             tag: 'Payments',     summary: 'Capture authorization',   deprecated: false },
  { method: 'POST',   path: '/v1/payments/{id}/refund',              tag: 'Payments',     summary: 'Refund payment',          deprecated: false },
  { method: 'POST',   path: '/v1/payments/{id}/void',                tag: 'Payments',     summary: 'Void payment',            deprecated: false },
  { method: 'GET',    path: '/v1/accounts',                          tag: 'Accounts',     summary: 'List accounts',           deprecated: false },
  { method: 'POST',   path: '/v1/accounts',                          tag: 'Accounts',     summary: 'Open account',            deprecated: false },
  { method: 'GET',    path: '/v1/accounts/{id}',                     tag: 'Accounts',     summary: 'Retrieve account',        deprecated: false },
  { method: 'GET',    path: '/v1/accounts/{id}/balance',             tag: 'Accounts',     summary: 'Get balance',             deprecated: false },
  { method: 'POST',   path: '/v1/transfers',                         tag: 'Transfers',    summary: 'Create transfer',         deprecated: false },
  { method: 'GET',    path: '/v1/transfers/{id}',                    tag: 'Transfers',    summary: 'Retrieve transfer',       deprecated: false },
  { method: 'POST',   path: '/v1/webhooks',                          tag: 'Webhooks',     summary: 'Register webhook',        deprecated: false },
  { method: 'DELETE', path: '/v1/webhooks/{id}',                     tag: 'Webhooks',     summary: 'Delete webhook',          deprecated: false },
  { method: 'GET',    path: '/v1/events',                            tag: 'Webhooks',     summary: 'List events',             deprecated: false },
  { method: 'POST',   path: '/v1/disputes/{id}/evidence',            tag: 'Disputes',     summary: 'Submit evidence',         deprecated: false },
  { method: 'GET',    path: '/v1/payouts/{id}',                      tag: 'Payouts',      summary: 'Retrieve payout',         deprecated: false },
  { method: 'POST',   path: '/v1/charges',                           tag: 'Payments',     summary: 'Create charge (legacy)',  deprecated: true },
];

const LEDGER_JOURNEYS = [
  {
    id: 'j_checkout',
    name: 'checkout-happy-path',
    file: 'journeys/checkout-happy-path.journey.ts',
    steps: 6,
    lastRun: { status: 'pass', ms: 842, ago: '2m' },
    tags: ['smoke', 'payments'],
  },
  {
    id: 'j_refund',
    name: 'refund-partial',
    file: 'journeys/refund-partial.journey.ts',
    steps: 4,
    lastRun: { status: 'pass', ms: 612, ago: '14m' },
    tags: ['payments'],
  },
  {
    id: 'j_3ds',
    name: '3ds-challenge-flow',
    file: 'journeys/3ds-challenge.journey.ts',
    steps: 8,
    lastRun: { status: 'fail', ms: 1203, ago: '1h' },
    tags: ['auth', 'smoke'],
  },
  {
    id: 'j_webhook',
    name: 'webhook-delivery-retry',
    file: 'journeys/webhook-delivery-retry.journey.ts',
    steps: 5,
    lastRun: { status: 'pass', ms: 2104, ago: '3h' },
    tags: ['webhooks'],
  },
  {
    id: 'j_transfer',
    name: 'transfer-insufficient-funds',
    file: 'journeys/transfer-insufficient-funds.journey.ts',
    steps: 4,
    lastRun: { status: 'pass', ms: 318, ago: '6h' },
    tags: ['negative', 'transfers'],
  },
  {
    id: 'j_dispute',
    name: 'dispute-evidence-upload',
    file: 'journeys/dispute-evidence-upload.journey.ts',
    steps: 7,
    lastRun: null,
    tags: ['disputes'],
  },
];

// A concrete run: checkout-happy-path
const CHECKOUT_STEPS = [
  {
    id: 's1',
    name: 'Open customer account',
    method: 'POST',
    url: '/v1/accounts',
    status: 201,
    ms: 142,
    size: '612 B',
    state: 'pass',
    extract: 'accountId = res.data.id',
    requestBody: { type: 'individual', email: 'ada@example.dev', currency: 'USD' },
    responseBody: { id: 'acc_01HT9K3M', type: 'individual', email: 'ada@example.dev', balance: { amount: 0, currency: 'USD' }, created: 1713488422 },
    logs: [],
  },
  {
    id: 's2',
    name: 'Fund account (test mode)',
    method: 'POST',
    url: '/v1/transfers',
    status: 201,
    ms: 88,
    size: '414 B',
    state: 'pass',
    extract: 'transferId = res.data.id',
    requestBody: { destination: '{{accountId}}', amount: 50000, currency: 'USD', source: 'test_pool' },
    responseBody: { id: 'tr_01HT9K3N', amount: 50000, currency: 'USD', status: 'posted' },
    logs: [{ level: 'log', text: 'funded 500.00 USD' }],
  },
  {
    id: 's3',
    name: 'Authorize payment',
    method: 'POST',
    url: '/v1/payments',
    status: 201,
    ms: 214,
    size: '728 B',
    state: 'pass',
    extract: 'paymentId = res.data.id',
    requestBody: { account: '{{accountId}}', amount: 12900, currency: 'USD', capture: false, payment_method: 'pm_card_visa' },
    responseBody: { id: 'pay_01HT9K3P', status: 'requires_capture', amount: 12900, currency: 'USD', amount_captured: 0 },
    logs: [],
  },
  {
    id: 's4',
    name: 'Capture payment',
    method: 'POST',
    url: '/v1/payments/{{paymentId}}/capture',
    status: 200,
    ms: 172,
    size: '698 B',
    state: 'pass',
    extract: null,
    requestBody: { amount_to_capture: 12900 },
    responseBody: { id: 'pay_01HT9K3P', status: 'succeeded', amount: 12900, amount_captured: 12900 },
    logs: [{ level: 'log', text: 'captured 129.00 USD' }],
  },
  {
    id: 's5',
    name: 'Verify balance',
    method: 'GET',
    url: '/v1/accounts/{{accountId}}/balance',
    status: 200,
    ms: 94,
    size: '186 B',
    state: 'pass',
    extract: null,
    requestBody: null,
    responseBody: { available: { amount: 37100, currency: 'USD' }, pending: { amount: 0, currency: 'USD' } },
    logs: [],
  },
  {
    id: 's6',
    name: 'Assert receipt webhook fired',
    method: 'GET',
    url: '/v1/events?type=payment.succeeded&related={{paymentId}}',
    status: 200,
    ms: 132,
    size: '342 B',
    state: 'pass',
    extract: null,
    requestBody: null,
    responseBody: { data: [{ id: 'evt_01HT9K3Q', type: 'payment.succeeded', delivered_at: 1713488424 }], has_more: false },
    logs: [{ level: 'log', text: '1 event delivered' }],
  },
];

// Environments
const LEDGER_ENVS = [
  { name: 'local',   active: true,  vars: 6 },
  { name: 'staging', active: false, vars: 9 },
  { name: 'ci',      active: false, vars: 5 },
];

// Recent runs (for overview + history)
const RECENT_RUNS = [
  { id: 'r_01', journey: 'checkout-happy-path',         status: 'pass', ms: 842,  ago: '2m',  env: 'local',   steps: 6, commit: 'a1b2c3d' },
  { id: 'r_02', journey: 'refund-partial',              status: 'pass', ms: 612,  ago: '14m', env: 'local',   steps: 4, commit: 'a1b2c3d' },
  { id: 'r_03', journey: '3ds-challenge-flow',          status: 'fail', ms: 1203, ago: '1h',  env: 'staging', steps: 8, commit: '7f2e1aa' },
  { id: 'r_04', journey: 'checkout-happy-path',         status: 'pass', ms: 798,  ago: '2h',  env: 'staging', steps: 6, commit: '7f2e1aa' },
  { id: 'r_05', journey: 'webhook-delivery-retry',      status: 'pass', ms: 2104, ago: '3h',  env: 'local',   steps: 5, commit: '7f2e1aa' },
  { id: 'r_06', journey: 'transfer-insufficient-funds', status: 'pass', ms: 318,  ago: '6h',  env: 'ci',      steps: 4, commit: 'e94d22b' },
  { id: 'r_07', journey: '3ds-challenge-flow',          status: 'pass', ms: 1088, ago: '8h',  env: 'ci',      steps: 8, commit: 'e94d22b' },
  { id: 'r_08', journey: 'checkout-happy-path',         status: 'pass', ms: 811,  ago: '1d',  env: 'ci',      steps: 6, commit: 'e94d22b' },
];

const PROJECTS = [
  { name: 'ledger-api',   path: '~/work/ledger/api',         active: true,  branch: 'main' },
  { name: 'billing-edge', path: '~/work/billing/edge',       active: false, branch: 'feat/dispute-flow' },
  { name: 'auth-svc',     path: '~/work/platform/auth-svc',  active: false, branch: 'main' },
  { name: 'mock-gateway', path: '~/sandbox/mock-gateway',    active: false, branch: 'main' },
];

Object.assign(window, {
  LEDGER_ENDPOINTS, LEDGER_JOURNEYS, CHECKOUT_STEPS, LEDGER_ENVS,
  RECENT_RUNS, PROJECTS,
});
