import { describe, expect, it } from "vitest";
import { parseGeneratedEndpoints } from "../src/server/specDrift.js";

describe("parseGeneratedEndpoints", () => {
  it("extracts every endpoint entry from a generated file", () => {
    const source = `// AUTO-GENERATED BY @usejourney/codegen — do not edit by hand.
import type { EndpointRef } from "@usejourney/core";
import type { paths } from "./models.js";

type JsonResponse<P, M> = unknown;

export const endpoints = {
  login: { method: "POST", path: "/auth/login", operationId: "login" } as unknown as EndpointRef<JsonResponse<"/auth/login", "post">>,
  getPet: { method: "GET", path: "/pet/{id}", operationId: "getPet" } as unknown as EndpointRef<JsonResponse<"/pet/{id}", "get">>,
  deletePet: { method: "DELETE", path: "/pet/{id}", operationId: "deletePet" } as unknown as EndpointRef<JsonResponse<"/pet/{id}", "delete">>,
} as const;
`;
    const parsed = parseGeneratedEndpoints(source);
    expect(parsed).toEqual([
      { method: "POST", path: "/auth/login", operationId: "login" },
      { method: "GET", path: "/pet/{id}", operationId: "getPet" },
      { method: "DELETE", path: "/pet/{id}", operationId: "deletePet" },
    ]);
  });

  it("returns [] for a file with no endpoint entries", () => {
    expect(parseGeneratedEndpoints("// empty")).toEqual([]);
  });
});
