import { operationName, uniqueName } from "./names.js";
import { HTTP_METHODS, type OpenApiDocument, type Operation } from "./types.js";

export function collectOperations(doc: OpenApiDocument): Operation[] {
  const paths = doc.paths ?? {};
  const taken = new Set<string>();
  const out: Operation[] = [];
  for (const [path, pathItem] of Object.entries(paths)) {
    if (!pathItem || typeof pathItem !== "object") continue;
    for (const method of HTTP_METHODS) {
      const op = (pathItem as Record<string, unknown>)[method];
      if (!op || typeof op !== "object") continue;
      const rawId = (op as { operationId?: unknown }).operationId;
      const id = uniqueName(
        operationName(method, path, typeof rawId === "string" ? rawId : undefined),
        taken,
      );
      out.push({ method, path, operationId: id });
    }
  }
  return out;
}

const HEADER = `// AUTO-GENERATED BY @usejourney/codegen — do not edit by hand.
import type { EndpointRef } from "@usejourney/core";
import type { paths } from "./models.js";

type JsonResponse<P extends keyof paths, M extends keyof paths[P]> =
  paths[P][M] extends { responses: infer R }
    ? R extends { 200: { content: { "application/json": infer T } } } ? T
    : R extends { 201: { content: { "application/json": infer T } } } ? T
    : R extends { 202: { content: { "application/json": infer T } } } ? T
    : unknown
    : unknown;
`;

export function renderEndpointsFile(operations: Operation[]): string {
  const entries = operations.map((op) => {
    const methodUc = op.method.toUpperCase();
    // Cast through unknown because runtime object carries no response-type info.
    return `  ${op.operationId}: { method: "${methodUc}", path: "${op.path}", operationId: "${op.operationId}" } as unknown as EndpointRef<JsonResponse<"${op.path}", "${op.method}">>,`;
  });
  return [
    HEADER,
    "export const endpoints = {",
    ...entries,
    "} as const;",
    "",
    "export type EndpointName = keyof typeof endpoints;",
    "",
  ].join("\n");
}
