import { mkdir, writeFile } from "node:fs/promises";
import { join } from "node:path";
import openapiTS, { astToString } from "openapi-typescript";
import { collectOperations, renderEndpointsFile } from "./emit-endpoints.js";
import { findPrefixOutliers } from "./lint.js";
import { loadSpec } from "./parse.js";

export interface GenerateOptions {
  /** Path to the OpenAPI spec file (YAML or JSON). */
  specPath: string;
  /** Directory where `endpoints.ts` and `models.ts` are written. */
  outDir: string;
}

export interface GenerateResult {
  modelsPath: string;
  endpointsPath: string;
  operationCount: number;
}

export async function generate(opts: GenerateOptions): Promise<GenerateResult> {
  const doc = await loadSpec(opts.specPath);
  const operations = collectOperations(doc);

  const outlier = findPrefixOutliers(operations);
  if (outlier) console.warn(outlier.message);

  const ast = await openapiTS(doc as Parameters<typeof openapiTS>[0]);
  const modelsSource = `// AUTO-GENERATED BY @journey/codegen — do not edit by hand.\n${astToString(ast)}`;
  const endpointsSource = renderEndpointsFile(operations);

  await mkdir(opts.outDir, { recursive: true });
  const modelsPath = join(opts.outDir, "models.ts");
  const endpointsPath = join(opts.outDir, "endpoints.ts");
  await writeFile(modelsPath, modelsSource, "utf8");
  await writeFile(endpointsPath, endpointsSource, "utf8");
  return { modelsPath, endpointsPath, operationCount: operations.length };
}

export { collectOperations, renderEndpointsFile } from "./emit-endpoints.js";
export { findPrefixOutliers, type PrefixLintFinding } from "./lint.js";
export { loadSpec } from "./parse.js";
export { operationName } from "./names.js";
export type { Operation } from "./types.js";
