#!/usr/bin/env tsx
/**
 * Walks docs/ for frontmatter `sources:` arrays and writes docs/SOURCES.md
 * with forward (doc -> files) and reverse (file -> docs) maps.
 *
 * Usage:
 *   tsx scripts/gen-doc-sources.ts           # write docs/SOURCES.md
 *   tsx scripts/gen-doc-sources.ts --check   # exit 1 if docs/SOURCES.md is stale
 */

import { readFile, readdir, stat, writeFile } from "node:fs/promises";
import { dirname, join, relative, resolve, sep } from "node:path";
import { fileURLToPath } from "node:url";
import matter from "gray-matter";

const __filename = fileURLToPath(import.meta.url);
const REPO_ROOT = resolve(dirname(__filename), "..");
const DOCS_DIR = resolve(REPO_ROOT, "docs");
const OUTPUT_PATH = join(DOCS_DIR, "SOURCES.md");
const SKIP_NAMES = new Set(["SOURCES.md"]);
const GENERATED_HEADER = "<!-- GENERATED by scripts/gen-doc-sources.ts — do not edit by hand. -->";

interface DocEntry {
  docPath: string; // posix path relative to docs/
  title: string;
  sources: string[]; // posix paths relative to repo root
}

async function walkMarkdown(dir: string): Promise<string[]> {
  const out: string[] = [];
  const entries = await readdir(dir, { withFileTypes: true });
  for (const e of entries) {
    const full = join(dir, e.name);
    if (e.isDirectory()) {
      out.push(...(await walkMarkdown(full)));
    } else if (e.isFile() && e.name.endsWith(".md") && !SKIP_NAMES.has(e.name)) {
      out.push(full);
    }
  }
  return out;
}

function toPosix(p: string): string {
  return p.split(sep).join("/");
}

async function collect(): Promise<DocEntry[]> {
  const files = await walkMarkdown(DOCS_DIR);
  files.sort();
  const entries: DocEntry[] = [];

  for (const file of files) {
    const raw = await readFile(file, "utf8");
    const parsed = matter(raw);
    const data = parsed.data as { title?: string; sources?: unknown };
    const docPath = toPosix(relative(DOCS_DIR, file));

    const rawSources = Array.isArray(data.sources) ? data.sources : [];
    const sources: string[] = [];
    for (const s of rawSources) {
      if (typeof s !== "string") {
        throw new Error(
          `${docPath}: frontmatter sources entry is not a string (${JSON.stringify(s)})`,
        );
      }
      const normalized = toPosix(s.trim());
      if (!normalized) continue;

      // Glob patterns (contain *) are passed through without disk verification.
      if (!normalized.includes("*")) {
        const abs = resolve(REPO_ROOT, normalized);
        try {
          await stat(abs);
        } catch {
          throw new Error(
            `${docPath}: frontmatter source "${normalized}" does not resolve to a file on disk`,
          );
        }
      }
      sources.push(normalized);
    }

    entries.push({
      docPath,
      title: typeof data.title === "string" && data.title ? data.title : docPath,
      sources,
    });
  }

  return entries;
}

function renderMarkdown(entries: DocEntry[]): string {
  const lines: string[] = [];
  lines.push(GENERATED_HEADER);
  lines.push("");
  lines.push("# Docs ↔ sources index");
  lines.push("");
  lines.push(
    "Auto-generated from the `sources:` frontmatter of each doc page. Edit the frontmatter, then run `pnpm --filter @usejourney/docs sources:gen`.",
  );
  lines.push("");

  // Forward map: doc -> sources
  lines.push("## By doc page");
  lines.push("");
  for (const entry of entries) {
    lines.push(`### \`${entry.docPath}\` — ${entry.title}`);
    if (entry.sources.length === 0) {
      lines.push("");
      lines.push("_No declared sources._");
      lines.push("");
      continue;
    }
    lines.push("");
    for (const src of entry.sources) {
      lines.push(`- \`${src}\``);
    }
    lines.push("");
  }

  // Reverse map: source -> docs
  const reverse = new Map<string, string[]>();
  for (const entry of entries) {
    for (const src of entry.sources) {
      if (!reverse.has(src)) reverse.set(src, []);
      reverse.get(src)!.push(entry.docPath);
    }
  }
  const reverseKeys = [...reverse.keys()].sort();

  lines.push("## By source file");
  lines.push("");
  lines.push("When a PR touches any of these paths, check the linked doc page(s) for updates.");
  lines.push("");

  if (reverseKeys.length === 0) {
    lines.push("_No source files are referenced yet._");
    lines.push("");
  } else {
    for (const src of reverseKeys) {
      lines.push(`### \`${src}\``);
      lines.push("");
      for (const doc of reverse.get(src)!.sort()) {
        lines.push(`- \`${doc}\``);
      }
      lines.push("");
    }
  }

  return lines.join("\n").replace(/\n+$/, "") + "\n";
}

async function main(): Promise<void> {
  const check = process.argv.includes("--check");
  const entries = await collect();
  const next = renderMarkdown(entries);

  if (check) {
    let existing = "";
    try {
      existing = await readFile(OUTPUT_PATH, "utf8");
    } catch {
      console.error(`docs/SOURCES.md is missing. Run: pnpm --filter @usejourney/docs sources:gen`);
      process.exit(1);
    }
    if (existing !== next) {
      console.error(
        `docs/SOURCES.md is out of date. Run: pnpm --filter @usejourney/docs sources:gen`,
      );
      process.exit(1);
    }
    console.log("docs/SOURCES.md is up to date.");
    return;
  }

  await writeFile(OUTPUT_PATH, next, "utf8");
  console.log(`Wrote ${relative(REPO_ROOT, OUTPUT_PATH)} (${entries.length} doc pages).`);
}

main().catch((err) => {
  console.error(err instanceof Error ? err.message : String(err));
  process.exit(1);
});
